replicaCount: 2

image:
  backend: pkmdocker857/ledger-backend:latest
  frontend: pkmdocker857/ledger-frontend:latest
  postgres: postgres:15-alpine

postgres:
  user: ledger
  password: ledgerpass
  db: ledgerdb

jwtSecret: supersecretkey

service:
  type: LoadBalancer
